# Author by airijia.com
# Basic
substitutions:
  # Modify variables based on your own settings
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

status_led:
  pin:
    number: 13
    inverted: True
switch:
  - platform: gpio
    name: $hostname switch_1
    pin: 12
    id: relay_1
binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: 0
      inverted: True
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle:
            id: relay_1
