# Author by airijia.com
# Basic 模块 点动功能 IO14/2 接物理开关
substitutions:
  # Modify variables based on your settings
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
  # inching delay period
  delay: 3s
  # Extra gpio, R1=14, R2=2
  io: '2'
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:


status_led:
  pin:
    number: 13
    inverted: True
switch:
  - platform: gpio
    pin: 12
    id: relay_1
    icon: "mdi:gate"
    on_turn_on:
      then:
        - delay: $delay
        - switch.turn_off: relay_1

binary_sensor:
  - platform: gpio
    id: button_0
    pin:
      number: 0
      inverted: True
      mode: INPUT_PULLUP
    on_click:
      then:
        - switch.turn_on: relay_1
  - platform: gpio
    id: button_2
    pin: 
      number: $io
      inverted: True
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.turn_on: relay_1
    on_release:
      then:
        - switch.turn_on: relay_1

