# Author by airijia.com
# Sonoff SV Momentary Switch
substitutions:
  # Modify variables based on your own settings
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
  # Switc
  delay: 500ms
  name: "Gate Remote"
  icon: "mdi:gate"
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

status_led:
  pin:
    number: 13
    inverted: True
switch:
  - platform: gpio
    pin: 12
    id: relay
  - platform: template
    name: $name
    icon: $icon
    turn_on_action:
    - switch.turn_on: relay
    - delay: $delay
    - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    id: button_0
    pin:
      number: 0
      inverted: True
      mode: INPUT_PULLUP
    on_click:
      then:
        - switch.turn_on: relay
        - delay: $delay
        - switch.turn_off: relay
