# Author by airijia.com
# SSD1306显示屏 + slogon
# 需要搭配 https://github.com/plutosherry/caiyun-weather-card 使用
substitutions:
  # 把这三项改成你自己的设置
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
  # I²C总线接线
  SDA: D2
  SCL: D1
  # 翻页延迟
  delay: 5s
  # 屏幕旋转读数，排针侧向上为 0°，排针侧向下为 180°
  rotation: 180°
  # 口号
  P1L1: IRONMAN
  P1L2: is the best!
  P2L1: CAPTAIN
  P2L2: sucks
esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

i2c:
  sda: $SDA
  scl: $SCL
  scan: False
time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Shanghai
    servers: ntp1.aliyun.com

font:
  - file: "arialbd"
    id: font_48
    size: 48
    glyphs: "0123456789:"
  - file: "helvetica"
    id: font_24
    size: 24
  - file: "helvetica"
    id: font_14
    size: 14
    glyphs: "0123456789:.-°|na"

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: $rotation
    id: display
    pages:
      - id: page1
        lambda: >-
          it.line(0, 49, 128, 49);
          it.strftime(0, 51, id(font_14), "%H:%M", id(sntp_time).now());
          it.filled_circle(54, 57, 3);
          it.circle(64, 57, 3);
          it.circle(74, 57, 3);

          it.print(0, 0, id(font_24), "$P1L1");
          it.print(128, 24, id(font_24), TextAlign::TOP_RIGHT, "$P1L2");
      - id: page2
        lambda: >-
          it.line(0, 49, 128, 49);
          it.strftime(0, 51, id(font_14), "%H:%M", id(sntp_time).now());
          it.circle(54, 57, 3);
          it.filled_circle(64, 57, 3);
          it.circle(74, 57, 3);

          it.print(0, 0, id(font_24), "$P2L1");
          it.print(128, 24, id(font_24),  TextAlign::TOP_RIGHT, "$P2L2");
      - id: page3
        lambda: >-
          it.line(0, 49, 128, 49);
          it.strftime(0, 51, id(font_14), "%H:%M", id(sntp_time).now());
          it.circle(54, 57, 3);
          it.circle(64, 57, 3);
          it.filled_circle(74, 57, 3);

          it.strftime(63, 24, id(font_48), TextAlign::CENTER, "%H:%M", id(sntp_time).now());
interval:
  - interval: $delay
    then:
      - display.page.show_next: display
      - component.update: display
binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: 0
      inverted: True
      mode: INPUT_PULLUP
    on_click:
      then:
        - display.page.show_next: display
        - component.update: display
