# Author by airijia.com
# 三合一气象传感器模块 HTU21D+BMP180+BH1750
# 组装说明 http://airijia.com/doc/#/diy/nodemcu/3in1
substitutions:
  # 把这三项改成你自己的设置
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

i2c:
  sda: D2
  scl: D1
  scan: False

sensor:
  # SHT30
  - platform: sht3xd
    temperature:
      name: $hostname temperature
    humidity:
      name: $hostname humidity
    address: 0x44
    update_interval: 60s
