# Author by airijia.com
# 三合一气象传感器模块 HTU21D+BMP180+BH1750
# + ssd1306 OLED 显示屏
# 组装说明 http://airijia.com/doc/#/diy/nodemcu/3in1
substitutions:
  # 把这三项改成你自己的设置
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
  # 屏幕旋转读数，排针侧向上为 0°，排针侧向下为 180°
  rotation: 0°
esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

i2c:
  sda: D2
  scl: D1
  scan: False
time:
  - platform: homeassistant
    # hass 的时间
    id: hass_time
    timezone: Asia/Shanghai

sensor:
  # SHT30
  - platform: sht3xd
    temperature:
      name: $hostname temperature
    humidity:
      name: $hostname humidity
    address: 0x44
    update_interval: 60s
image:
  - file: "mdi:thermometer"
    id: thermometer
    resize: 32x32
  - file: "mdi:water-percent"
    id: water
    resize: 32x32
font:
  - file: "helvetica"
    id: font_32
    size: 32
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1s
    rotation: $rotation
    lambda: >-
      it.image(0, 0, id(thermometer));
      it.printf(32, 16, id(font_32), "%.1f°C", id(temperature).raw_state);
      it.image(0, 32, id(water));
      it.printf(32, 48, id(font_32), "%.1f%%", id(humidity)