# Author by airijia.com
# 4CH 模块基本功能
substitutions:
  # 把这三项改成你自己的设置
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

status_led:
  pin:
    number: 13
    inverted: True
switch:
  - platform: gpio
    name: $hostname switch_1
    pin: GPIO12
    id: relay_1
  - platform: gpio
    name: $hostname switch_2
    pin: GPIO5
    id: relay_2
  - platform: gpio
    name: $hostname switch_3
    pin: GPIO4
    id: relay_3
  - platform: gpio
    name: $hostname switch_4
    pin: GPIO15
    id: relay_4
binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      inverted: True
      mode: INPUT_PULLUP
    on_press :
      then:
        - switch.toggle:
            id: relay_1
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      inverted: True
      mode: INPUT_PULLUP
    on_press :
      then:
        - switch.toggle:
            id: relay_2
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      inverted: True
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle:
            id: relay_3
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      inverted: True
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle:
            id: relay_4
