# Author by 麦呆
substitutions:
  # 把这三项改成你自己的设置
  hostname: '666'
  ssid: 'airi'
  password: 'airijia.com'
  # SCL 接到esp 的 RX上，sda接到 IO2上
  sda: '2'
  scl: '3'
esphomeyaml:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
  id: wifi
api:
  password: ''
  reboot_timeout: 0s
ota:
  password: ''  
logger:
i2c:
  sda: $sda
  scl: $scl
  scan: False
sensor:
  - platform: bh1750
    name: $hostname_illuminance_1
    address: 0x23
    resolution:  0.5
    update_interval:  15s